version: '2'
services:
  PostgreSQL:
    restart: always
    image: silverbulleters/ya-docker-postgresql-1c:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - PG_PASSWORD=somepass
      - DB_USER=onecuser
      - DB_PASS=anotherpass
      - DB_NAME=powa,mamonsu
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
      - REPLICATION_SSLMODE=
      - PG_TUNE_BY_MAMONSU=true
      - PG_MAX_CONNECTION=130
      - SSH_ENABLE=0

    volumes:
      - pg-data-master:/var/lib/postgresql/9.6/main
      - pg-temptbl-master:/var/lib/postgresql/temptblspc
      - pg-v81cdata-master:/var/lib/postgresql/v81c_data
      - pg-v81cindex-master:/var/lib/postgresql/v81c_index
      - pg-log-master:/var/log/postgresql

  PostgreSQLSlave:
    image: silverbulleters/ya-docker-postgresql-1c:latest
    links: 
      - PostgreSQL:master
    environment: 
      - REPLICATION_MODE=slave
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
      - REPLICATION_HOST=master
      - REPLICATION_PORT=5432
      - REPLICATION_SSLMODE=prefer
    volumes:
      - pg-data-slave:/var/lib/postgresql/9.6/main
      - pg-temptbl-slave:/var/lib/postgresql/temptblspc
      - pg-v81cdata-slave:/var/lib/postgresql/v81c_data
      - pg-v81cindex-slave:/var/lib/postgresql/v81c_index
      - pg-log-slave:/var/log/postgresql

  PgAdminDBA:
    image: dpage/pgadmin4
    ports: 
      - 8880:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=team@silverbulleters.org
      - PGADMIN_DEFAULT_PASSWORD=somepass
    #  - PGADMIN_ENABLE_TLS=
    #  - PGADMIN_SERVER_NAME=
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    links: 
      - PostgreSQL:master
      - PostgreSQLSlave:slave

  PowaWeb:
      build: 
        context: powa-web
      image: silverbulleters/powa-web:latest
      ports:
        - 8899:8888
      links:
        - PostgreSQL:master
        - PostgreSQLSlave:slave

  pghero-db1:
    image: ankane/pghero
    environment:
      - DATABASE_URL=postgres://postgres:somepass@master-db:5432/frag-20
    links:
      - PostgreSQL:master-db
    ports:
      - 10000:8080
    
  
  mamonsu:
    container_name: mamonsu
    build: 
      context: mamonsu
    image: silverbulleters/mamonsu:latest
    ports:
      - 10050:10050
    links:
      - PostgreSQL:master

volumes:
   pg-data-master:
   pg-temptbl-master:
   pg-v81cdata-master:
   pg-v81cindex-master:
   pg-log-master:

   pg-data-slave:
   pg-temptbl-slave:
   pg-v81cdata-slave:
   pg-v81cindex-slave:
   pg-log-slave:

   pgadmin-data: