filebeat.config:
  prospectors:
    path: /usr/share/filebeat/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: /usr/share/filebeat/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.logstash:
  hosts: ["127.0.0.1:5000"]
